### ISSUE TITLE
Remove the "Mailings" page, as it is no longer active.

### ISSUE THREAD

**Issue by Rahler** [kgoess/dance-scheduler#14]
https://bacds.org/mailings/

**Comment by Rahler** [comment]
also https://bacds.org/current-mailing

**Comment by kgoess** [comment]
Ok, I commented out the links to current-mailing in these three pages: content.html organization/shared/menu.html series/shared/menu.html

I edited mailings/content.html so that the only thing left is the archives.

I changed mailings/current-mailing/index.html to be a HTML META redirect to groups.io
